name: iOS deploy

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Arc Clone
        run: |
          git submodule update --init --depth=10
          cd work
          ../scripts/applyPatches.sh
          cd ..
          git clone https://github.com/Anuken/Arc.git
      - name: iOS deploy
        run: |
          cd work
          ./gradlew ios:deploy
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: work/ios/build/robovm/IOSLauncher.ipa