name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12
          cache-read-only: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: Set env
        run: |
          git config --global user.email "ci@noreply.example.com"
          git config --global user.name "github_actions"
          RELEASE_VERSION=$(date +'%Y.%m').X${GITHUB_RUN_NUMBER}
          echo "RELEASE_TAG=$RELEASE_VERSION"
          
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_TAG=v${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "${{ secrets.KEYSTORE_BASE64 }}" | openssl enc -d -base64 -in - -out bekeystore.jks
      - name: Build
        env:
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
          keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
          keystore_alias: MindustryX
        run: |
          git submodule update --init --depth=10
          cd work
          ../scripts/applyPatches.sh
          gradle -Pbuildversion=${RELEASE_VERSION} --parallel \
            desktop:dist server:dist core:genLoaderModAll android:assembleRelease 
          
          cd ..
          mkdir artifacts
          mv work/desktop/build/libs/Mindustry.jar artifacts/MindustryX-${{env.RELEASE_VERSION}}-Desktop.jar
          mv work/server/build/libs/server-release.jar artifacts/server-${{env.RELEASE_VERSION}}.jar
          mv work/core/build/distributions/MindustryX.loader.dex.jar artifacts/dexed-MindustryX-${{env.RELEASE_VERSION}}.loader.jar
          mv work/android/build/outputs/apk/release/android-release.apk artifacts/MindustryX-${{env.RELEASE_VERSION}}-Android.apk
#      - name: Update Tag
#        uses: rickstaa/action-create-tag@v1
#        with:
#          tag: ${{ env.RELEASE_TAG }}
#          force_push_tag: true
      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_VERSION }}
          target_commitish: ${{github.sha}}
          files: artifacts/*
          draft: true
      - uses: oven-sh/setup-bun@v1
